# fly.toml app configuration file generated for crowdfunding-frontend on 2023-09-19T18:42:14+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crowdfunding-frontend"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
